apiVersion: v1
kind: Service
metadata:
  name: fn
  labels:
    app: fn
spec:
  ports:
  - port: 3000
    protocol: TCP
  clusterIP: None
  selector:
    app: fn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fn
  labels:
    app: fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fn
  template:
    metadata:
      labels:
        app: fn
    spec:
      containers:
      - name: fn
        image: cr.nrtn.dev/sandbox/fn
